version: '3'

services:

    app:
        build: .
        container_name: app
        volumes: 
            - .:/var/www
        networks: 
            - app-network
        depends_on: 
            - mysql
            - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "8000:80"
        volumes:
            - .:/var/www
        networks: 
            - app-network
        depends_on: 
            - app

    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app-network  
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql

    redis:
        image: redis:alpine
        expose:
            - 6379s
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge
    